2024-10-18 22:34:07,887 | INFO | test_run" выполнен успешно
2024-10-18 22:34:07,887 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/antonystark/Python rpojects/Lessons/pythonProject/module_12/tests_12_4/tests_12_4.py", line 28, in test_run
    runner = Runner(1, 5)
             ^^^^^^^^^^^^
  File "/Users/antonystark/Python rpojects/Lessons/pythonProject/module_12/tests_12_4/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-18 22:34:07,888 | INFO | test_walk" выполнен успешно
2024-10-18 22:34:07,888 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/antonystark/Python rpojects/Lessons/pythonProject/module_12/tests_12_4/tests_12_4.py", line 17, in test_walk
    runner = Runner('Run_Obi', -1)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antonystark/Python rpojects/Lessons/pythonProject/module_12/tests_12_4/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
